### ISSUE TITLE
Codestyle

### ISSUE THREAD

**Issue by abendt** [muhammad83/doThis#5]
We want to enforce a certain codestyle to ensure consistency. Also helpful to minimize conflicts b/c of different formatting when merging. 

My recommendation is to use spotless here as it supports a number of languages.

AC:
* plugin to format sourcecode is integrated into the build
* code style check is enforced in CI build 
   * build should break if code is not formatted correctly

**Comment by muhammad83** [comment]
the plugin is working locally and i think on the build too. there is no code to check if it is. Should i park it for now or should i raise a pull request?

**Comment by abendt** [comment]
There is some code in the class `Application.java` you can use:

Try if a poorly formatted file (just add some arbitrary formatting to `Application.java`) will cause the build to fail.

**Comment by muhammad83** [comment]
i can't get spotless to work, i am trying this https://arc.net/l/quote/mrfurndh and it doesn't work. i keep getting this error ```
Could not determine the dependencies of task ':spotlessApply'.
> Could not create task ':spotlessJavaApply'.
   > Could not create task ':spotlessJava'.
      > java.nio.file.NoSuchFileException: /Users/muhammadqureshi/Documents/personal/doThis/eclipse-import-order.txt

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 559ms
```

**Comment by abendt** [comment]
you don't need to explicitely call the `spotlessCheck` task in `build.yml`.

Gradle will already call it during `build`

I have added the tasktree plugin to the branch. It allows you to see the dependencies of a gradle task:

```
❯ gw build taskTree

> Task :taskTree

------------------------------------------------------------
Root project 'doThis'
------------------------------------------------------------

:build
+--- :assemble
|    +--- :bootJar
|    |    +--- :classes
|    |    |    +--- :compileJava
|    |    |    \--- :processResources
|    |    +--- :compileJava *
|    |    \--- :resolveMainClassName
|    |         +--- :classes *
|    |         \--- :compileJava *
|    \--- :jar
|         +--- :classes *
|         \--- :compileJava *
\--- :check
     +--- :spotlessCheck
     |    \--- :spotlessKotlinCheck
     |         \--- :spotlessKotlin
     |              \--- :spotlessInternalRegisterDependencies
     \--- :test
          +--- :classes *
          +--- :compileJava *
          +--- :compileTestJava
          |    +--- :classes *
          |    \--- :compileJava *
          \--- :testClasses
               +--- :compileTestJava *
               \--- :processTestResources
```

As you can see `build` depends on `check` which depends on `spotlessCheck`.

Another way to better see what gradle is doing it to run it with info: `gw build -i`. This is quite verbose but will print out the names of all tasks ...


The spotless plugin does not do the formatting itself. It delegates to a number of existing formatters to do the job.
Initially you just added the spotless plugin without additional config. In my understanding that will do nothing.

Now you have added ktlint. I think ktlint is only for kotlin code not for java, so you should use a formatter that supports java. See [here](https://github.com/diffplug/spotless/tree/main/plugin-gradle#java) for the java related configuration.

 I see eclipse mentioned in the error message. Looks you tried out the eclipse formatter? Its possible that it requires additional configuration, haven't used it myself yet. Try to use the google formatter. I think it should work without additional config ...

**Comment by muhammad83** [comment]
Thank you. I wasn't sure klint would work but I couldn't find any Java one. Maybe my google search was not good enough. 

What's ur take on enabling code companion. An artificial assistant which helps in code completion. Should I use it or stay clear of it?

**Comment by abendt** [comment]
I am also using the smart complete that's available in intellij. 

Good to use tools if they help you. Just try it out. 

Of course you should always review the generated code so you fully understand what it does

**Comment by muhammad83** [comment]
sorry for being AWOL. There is no excuse but i will still try and justify it with "too much happening". My son's term was ending and there were a lot of afterschool events which just kept me busy during evening. Also the new job is something I have never done before. Its platform testing and I have never worked in any of the techs they are using. To add it up, my son's summer vacations have also started and I am in Portugal right now. and that means I have finally time. So here is the pull request and it is working fine with google java format.
